-- ════════════════════════════════════════════════════════════════════════
--  Programa 5S + SOL — schema completo (Supabase / PostgreSQL)
--  Rode este arquivo UMA vez num projeto Supabase novo. Depois, copie a URL
--  e a chave "anon" para src/services/supabase.js. Pronto para usar.
--  Seguro de rodar mais de uma vez.
-- ════════════════════════════════════════════════════════════════════════

-- ── Base de áreas: Planta → Fábrica → Setor → Linha/Máquina ──────────────
create table if not exists public.cadastro_planta_area (
    id         bigint generated by default as identity primary key,
    created_at timestamptz default now(),
    planta     text,
    fabrica    text,
    setor      text,
    maquina    text
);

-- Linha = união de máquinas. `tipo` diz o que o registro é ('linha' ou
-- 'maquina'; nulo = setor inteiro) e `linha_id` aponta a máquina para a linha
-- que ela compõe. Apagar a linha solta as máquinas, não as apaga.
alter table public.cadastro_planta_area add column if not exists tipo text;
alter table public.cadastro_planta_area add column if not exists linha_id bigint
    references public.cadastro_planta_area(id) on delete set null;
create index if not exists cadastro_planta_area_linha_idx on public.cadastro_planta_area(linha_id);
-- Registros antigos: o nome decide ("LINHA 07" é linha, o resto é máquina).
update public.cadastro_planta_area
   set tipo = case when maquina ~* '^\s*linha' then 'linha' else 'maquina' end
 where tipo is null and maquina is not null and trim(maquina) <> '';

-- ── Auditorias 5S + SOL ──────────────────────────────────────────────────
create table if not exists public.cinco_s_auditoria (
    id             bigint generated by default as identity primary key,
    created_at     timestamptz default now(),
    updated_at     timestamptz default now(),
    titulo         text,
    planta         text,
    fabrica        text,
    setor          text,
    maquina        text,               -- linha/máquina (opcional; vazio = setor inteiro)
    auditor        text,
    acompanhante   text,
    data_auditoria date,
    status         text default 'aberta',   -- aberta | concluida
    respostas      jsonb default '{}'::jsonb,   -- { itemId: nota 0-5 }
    observacoes    jsonb default '{}'::jsonb,   -- { itemId: texto do desvio }
    fotos          jsonb default '{}'::jsonb,   -- { itemId: [dataURL...] }
    planos         jsonb default '[]'::jsonb,   -- plano de ação 5S + SOL
    score          numeric,                     -- Score 5S (0-100)
    scores         jsonb default '{}'::jsonb,   -- { sensoId:%, sol_*, solar, geral, sol_geral }
    analise_ia     text,                        -- Resumo Executivo (gerado por IA, editável)
    criado_por     text
);

-- Bancos criados antes destas colunas: adiciona sem perder dados.
alter table public.cinco_s_auditoria add column if not exists maquina       text;
alter table public.cinco_s_auditoria add column if not exists analise_ia    text;

create index if not exists idx_5s_status on public.cinco_s_auditoria (status);
create index if not exists idx_5s_area   on public.cinco_s_auditoria (planta, fabrica, setor, maquina);

-- Atualiza updated_at automaticamente
create or replace function public.set_updated_at_5s() returns trigger as $$
begin new.updated_at = now(); return new; end; $$ language plpgsql;
drop trigger if exists trg_5s_updated on public.cinco_s_auditoria;
create trigger trg_5s_updated before update on public.cinco_s_auditoria
    for each row execute function public.set_updated_at_5s();

-- ── Acesso (app sem login → acesso via chave anon) ───────────────────────
alter table public.cadastro_planta_area enable row level security;
alter table public.cinco_s_auditoria   enable row level security;

drop policy if exists area_all on public.cadastro_planta_area;
create policy area_all on public.cadastro_planta_area for all using (true) with check (true);

drop policy if exists aud_all on public.cinco_s_auditoria;
create policy aud_all on public.cinco_s_auditoria for all using (true) with check (true);

notify pgrst, 'reload schema';
